### ISSUE TITLE
Diagram is shown twice when using kotlin.check

### ISSUE THREAD

**Issue by rocketraman** [bnorm/kotlin-power-assert#106]
When doing tests in `commonTest` we don't have access to `kotlin.assert`, which appears to only be available on JVM and native.

So, I tried to use `check` instead, which works, but shows the diagram twice:

```
  @Test
  fun foo() {
    check("foo" == "bar") { "Failed foo=bar" }
  }
```

```
Failed foo=bar
check("foo" == "bar") { "Failed foo=bar" }
            |
            false
java.lang.IllegalStateException: Failed foo=bar
check("foo" == "bar") { "Failed foo=bar" }
            |
            false
```

Also shows twice if the lazyMessage param is not given.

**Comment by bnorm** [comment]
I think this may be an IDE oddity, rather than something specific to kotlin-power-assert. I think your IDE (looks like an output from IntelliJ) is showing you the message of the exception the test is failing with and then dumping the stacktrace of the exception which also includes the error message. I suspect if you remove kotlin-power-assert from your build you will observe the same behavior, just without the diagram.

**Comment by rocketraman** [comment]
> I think this may be an IDE oddity, rather than something specific to kotlin-power-assert.

Yep, you're right. Weird that I've never noticed that before. Sorry for the noise!

**Comment by rocketraman** [comment]
More context if anyone else comes upon this in the future:

* https://github.com/google/truth/issues/680
* https://youtrack.jetbrains.com/issue/IDEA-238472
*
