### ISSUE TITLE
Static functions do not seem to work

### ISSUE THREAD

**Issue by bnorm** [bnorm/kotlin-power-assert#52]
Static functions from the JUnit 5 Assertions class don't seem to be diagramed. Add some unit tests for static functions to make sure they work correctly. And fix any bugs found.

**Comment by TWiStErRob** [comment]
Note there are two of them:
There's `AssertionsKt`: https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/kotlin/org/junit/jupiter/api/Assertions.kt

And `Assertions`: https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java

I guess the problem is with the latter?

**Comment by bnorm** [comment]
Correct. I briefly tried it at least and it didn't seem to be working for the latter. Would be good to double check with some unit tests and make sure it always works. Could just be some problems with the plugin trying to find an appropriate overload.
